ARG BASE_IMAGE="ghcr.io/kas-lab/kasm-jammy:latest"
FROM $BASE_IMAGE

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV KASM_RX_HOME $STARTUPDIR/kasmrx
ENV INST_SCRIPTS $STARTUPDIR/install

###Add Sudo
RUN apt-get update \
    && apt-get install -y sudo \
    && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && rm -rf /var/lib/apt/list/*

###Add the USER env var
RUN echo 'USER=whoami; export USER' >> $HOME/.bashrc

### Install Tools
COPY ./docker/src/ubuntu/install/tools $INST_SCRIPTS/tools/
RUN bash $INST_SCRIPTS/tools/install_tools_deluxe.sh  && rm -rf $INST_SCRIPTS/tools/

### Install Visual Studio Code
COPY ./docker/src/ubuntu/install/vs_code $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_vs_code.sh  && rm -rf $INST_SCRIPTS/vs_code/

### Install Gazebo
COPY ./docker/src/ubuntu/install/gazebo $INST_SCRIPTS/gazebo/
RUN bash $INST_SCRIPTS/gazebo/install_gazebo_ignition.sh  && rm -rf $INST_SCRIPTS/gazebo/

### Install ROS2
COPY ./docker/src/ubuntu/install/ros2 $INST_SCRIPTS/ros2/
RUN bash $INST_SCRIPTS/ros2/install_ros2_humble.sh  && rm -rf $INST_SCRIPTS/ros2/


RUN $STARTUPDIR/set_user_permission.sh $HOME

RUN chown 1000:0 $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

### Install Ardusub and Arduplugin and suave
WORKDIR $INST_SCRIPTS
COPY ./docker/src/ubuntu/install/ardusub $INST_SCRIPTS/ardusub/
RUN bash $INST_SCRIPTS/ardusub/install_ardusub.sh

RUN bash $INST_SCRIPTS/ardusub/install_arduplugin.sh

ENV GZ_VERSION="garden"
RUN mkdir -p $HOME/suave_ws/src
COPY suave.rosinstall $HOME/suave_ws/suave.rosinstall
WORKDIR $HOME/suave_ws/
RUN vcs import src < suave.rosinstall --recursive

RUN rm -rf $HOME/suave_ws/src/suave/
COPY runner/ $HOME/suave_ws/src/suave/runner/
COPY suave/ $HOME/suave_ws/src/suave/suave/
COPY suave_missions/ $HOME/suave_ws/src/suave/suave_missions/
COPY suave_metacontrol/ $HOME/suave_ws/src/suave/suave_metacontrol/
COPY suave_msgs/ $HOME/suave_ws/src/suave/suave_msgs/

COPY ./docker/src/ubuntu/install/suave/install_suave_deps.sh $INST_SCRIPTS/suave/install_suave_deps.sh
RUN bash $INST_SCRIPTS/suave/install_suave_deps.sh
COPY ./docker/src/ubuntu/install/suave/install_suave.sh $INST_SCRIPTS/suave/install_suave.sh
RUN bash $INST_SCRIPTS/suave/install_suave.sh

RUN sudo apt autoremove -y && sudo rm -rf /var/lib/apt/lists/

WORKDIR /home/kasm-user/suave_ws/src/suave/runner/

CMD ["--tail-log"]
