# Use the official ROS 2 Humble base image.
FROM ros:humble-ros-core-jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    wget \
    vim \
    git \
    python3-pip \
    python3-vcstool \
    python3-rosdep \
    xvfb \
    htop \
    mesa-utils \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    libglx-mesa0 \
    ros-dev-tools \
    ros-humble-ament-cmake-flake8 \
    python3-flake8-* \
    && rm -rf /var/lib/apt/lists/*

RUN rosdep init

RUN sudo apt-get update && sudo apt-get install -y \
    openjdk-25-jdk \
    && sudo rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-25-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

### Install Gazebo
RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

RUN bash -c 'curl https://raw.githubusercontent.com/osrf/osrf-rosdep/master/gz/00-gazebo.list --output /etc/ros/rosdep/sources.list.d/00-gazebo.list'
ENV GZ_VERSION=harmonic

RUN apt update && apt install -y \
    gz-harmonic \
    ros-humble-ros-gzharmonic \
    && rm -rf /var/lib/apt/lists/

### Add the USER env var
RUN groupadd -g 1000 ubuntu-user \
    && adduser --disabled-password --gid 1000 --uid 1000 --gecos '' ubuntu-user \
    && adduser ubuntu-user sudo

RUN echo 'ubuntu-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
ENV HOME=/home/ubuntu-user
USER ubuntu-user
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR $HOME

ARG ARDUSUB_COMMIT=571e8c7bd3793fce1bc5184a2f6586feb8a616e5
ARG ARDUPILOT_GAZEBO_COMMIT=082a0fe231f6e63bc8d1598f1cba461d9e2ea7f5

COPY --chown=ubuntu-user:ubuntu-user requirements.txt $HOME/requirements.txt

# Install ArduSub
RUN git clone https://github.com/ArduPilot/ardupilot.git
WORKDIR $HOME/ardupilot
RUN git checkout $ARDUSUB_COMMIT
RUN git submodule update --init --recursive
RUN USER=ubuntu-user Tools/environment_install/install-prereqs-ubuntu.sh -y

RUN sudo pip3 install -r $HOME/requirements.txt

ENV PATH=/opt/gcc-arm-none-eabi-10-2020-q4-major/bin:$PATH
ENV PATH=$PATH:$HOME/ardupilot/Tools/autotest
ENV PATH=/usr/lib/ccache:$PATH

RUN ["/bin/bash", "-c", "cd $HOME/ardupilot && ./waf configure && make sub"]

# ArduPilot Gazebo plugin dependencies
RUN sudo apt-get update && sudo apt-get install -y \
    libgz-sim8-dev \
    rapidjson-dev \
    libopencv-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-libav \
    gstreamer1.0-gl \
    && sudo rm -rf /var/lib/apt/lists/*

# Install ArduPilot Gazebo plugin
WORKDIR $HOME
RUN git clone https://github.com/ArduPilot/ardupilot_gazebo && \
    cd ardupilot_gazebo && \
    git checkout $ARDUPILOT_GAZEBO_COMMIT && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && \
    make -j4

ENV GZ_SIM_SYSTEM_PLUGIN_PATH=$HOME/ardupilot_gazebo/build
ENV GZ_SIM_RESOURCE_PATH=$HOME/ardupilot_gazebo/models:$HOME/ardupilot_gazebo/worlds

# Import external dependencies from suave.repos, then copy this checkout.
RUN mkdir -p $HOME/suave_ws/src
COPY --chown=ubuntu-user:ubuntu-user suave.repos $HOME/suave_ws/suave.repos
WORKDIR $HOME/suave_ws
RUN vcs import src < suave.repos --recursive

RUN rm -rf $HOME/suave_ws/src/suave && mkdir -p $HOME/suave_ws/src/suave
COPY --chown=ubuntu-user:ubuntu-user suave/ $HOME/suave_ws/src/suave/suave/
COPY --chown=ubuntu-user:ubuntu-user suave_managing/ $HOME/suave_ws/src/suave/suave_managing/
COPY --chown=ubuntu-user:ubuntu-user suave_metrics/ $HOME/suave_ws/src/suave/suave_metrics/
COPY --chown=ubuntu-user:ubuntu-user suave_missions/ $HOME/suave_ws/src/suave/suave_missions/
COPY --chown=ubuntu-user:ubuntu-user suave_monitor/ $HOME/suave_ws/src/suave/suave_monitor/
COPY --chown=ubuntu-user:ubuntu-user suave_msgs/ $HOME/suave_ws/src/suave/suave_msgs/
COPY --chown=ubuntu-user:ubuntu-user suave_runner/ $HOME/suave_ws/src/suave/suave_runner/
COPY --chown=ubuntu-user:ubuntu-user suave_tools/ $HOME/suave_ws/src/suave/suave_tools/
COPY --chown=ubuntu-user:ubuntu-user runner/ $HOME/suave_ws/src/suave/runner/

RUN ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash \
    && sudo apt update \
    && rosdep update \
    && rosdep install --from-paths src --ignore-src -r -y \
    && sudo rm -rf /var/lib/apt/lists/"]

RUN ["/bin/bash", "-c", "sudo ./src/mavros/mavros/scripts/install_geographiclib_datasets.sh"]

RUN pip3 install -r $HOME/requirements.txt

# ArduPilot installs a newer user-local flake8 which is incompatible with the
# Ubuntu Jammy flake8 plugins used by the ROS 2 Humble lint environment.
RUN pip3 install flake8==4.0.1

RUN ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash \
    && colcon build --symlink-install \
    && echo 'source ~/suave_ws/install/setup.bash' >> ~/.bashrc"]

RUN sudo apt autoremove -y && sudo rm -rf /var/lib/apt/lists/

WORKDIR $HOME/suave_ws/
