name: documentation

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@0.3.5
        id: action_ros_ci_step
        with:
          package-name: suave suave_msgs suave_missions suave_metacontrol system_modes mavros mavros_wrapper mros2_reasoner mros2_msgs
          target-ros2-distro: humble
          skip-tests: true
          vcs-repo-file-url: https://raw.githubusercontent.com/kas-lab/suave/main/suave.rosinstall
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-autopackagesummary myst-parser
      - name: Sphinx build
        run: |
          source ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/install/setup.bash && sphinx-build docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
