name: tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_docker:
    name: Build and test suave pkgs
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build pkgs
        uses: ros-tooling/action-ros-ci@0.4.8
        with:
          package-name: |
            suave
            suave_bt
            suave_metacontrol
            suave_metrics
            suave_missions
            suave_monitor
            suave_msgs
            suave_none
            suave_random
            suave_runner
            suave_tools
          target-ros2-distro: humble
          vcs-repo-file-url: ${{ github.workspace }}/suave.repos
